### ISSUE TITLE
Connection.end() causes an emit of ECONNRESET

### ISSUE THREAD

**Issue by OJezu** [postwait/node-amqp#300]
When I run some of the tests, e.g

  node test/test-basic-return.js

I get

```
/home/ch/node_modules/amqp/node_modules/longjohn/dist/longjohn.js:184
        throw e;
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at onread (net.js:556:19)
---------------------------------------------
    at module.exports.run (/home/ch/node_modules/amqp/test/harness.js:49:23)
    at Object.<anonymous> (/home/ch/node_modules/amqp/test/test-basic-return.js:1:84)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module._load (module.js:312:12)
    at Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

It seems it is connected to #295 and #246, however the code from #248 does not solve it.

It is a hell of a bug, because it caused me to look for a few hours for a bug in exchange.publish, and then it turned out it is some networking stuff happening upon `connection.end()`.

**Comment by davidsielert** [comment]
No fix for this ?? Kind of hard to run a tutorial that doesn't work ..

**Comment by pruthvireddypuresoftware** [comment]
test/test-basic-return.js: Error: read ECONNRESET
    at TCP.onread (net.js:660:25)
---------------------------------------------
    at Object.run (/node/node-amqp/test/harness.js:49:23)
    at Object.<anonymous> (/node/node-amqp/test/test-basic-return.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
Facing above issue in debian, nodejs v10.8 and RabbitMQ 3.3.5. Downloaded the current commit and connection.js file has destroy function called.
case methods.connectionCloseOk:
      debug && debug("Received close-ok from server, closing socket");
      this.socket.end();
      this.socket.destroy();
      break;

Please suggest me any other solution. Thanks.
