### ISSUE TITLE
connection.disconnect() fires the error handler with connection reset

### ISSUE THREAD

**Issue by Gilwyad** [postwait/node-amqp#462]
let connection = amqp.createConnection(...);
    connection.on('ready', function () {
        connection.exchange(...,
                            function () {
                                connection.queue(...,
                                                 function (q, messageCount, consumerCount) {
                                                     connection.disconnect();
                                                 });
                            });
    });
    
    connection.on('error', function(e) {
        console.log(e);
    }

How should I cleanly disconnect while also handling errors?

**Comment by soichih** [comment]
Same issue. When I call `connection.disconnect()` I receive an error event.

```
 Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)

```

I have a script that uses amqp and script and I need to terminate after all processing is done. However, calling disconnect won't kill the amqp's  even loop(?) so my script keeps running. calling disconnect() doesn't seem to end the event loop in this case.

**Comment by mcgG** [comment]
Same issue, calling `disconnect()` will trigger `reconnect()` so a new socket will open, this will cause mocha (>= 3.x) unit test cannot exit properly without `--exit`

**Comment by mcgG** [comment]
A temporary way to fix this issue is to call 
`self.connection.setImplOptions({reconnect: false});`
before
`connection.disconnect()`
Then, connection will be reconnected by disconnect()'s exception

**Comment by soichih** [comment]
Is there any update on this issue? I am still hit by this issue. (I am just killing the App manually at the end)
